### PR TITLE
fix: support unencrypted PKCS#8 keys again

### LINKED ISSUE #452: "InvalidAsn1Error: encoding too long" after updating to 2.8.2
I recently wrote about another issue (#449 ), and after updating from 2.7.7 to the latest 2.8.2, we are still experiencing issues

Same works fine with previous version, but we need to update for the security patches that are in later releases

Call:
serviceProvider.createLoginRequest(identityProvider, 'redirect', (logoutRequestTemplate) => { ... })

Failure exception:
Exception: InvalidAsn1Error: encoding too long
Stack: InvalidAsn1Error: encoding too long
    at newInvalidAsn1Error (C:\...\node_modules\asn1\lib\ber\errors.js:7:13)
    at Reader.readLength (C:\...\node_modules\asn1\lib\ber\reader.js:103:13)
    at Reader.readSequence (C:\...\node_modules\asn1\lib\ber\reader.js:136:16)
    at Object.privateImport (C:\...\node_modules\node-rsa\src\formats\pkcs1.js:68:16)
    at Object.detectAndImport (C:\...\node_modules\node-rsa\src\formats\formats.js:64:48)     
    at NodeRSA.module.exports.NodeRSA.importKey (C:\...\node_modules\node-rsa\src\NodeRSA.js:183:22)
    at new NodeRSA (C:\...\node_modules\node-rsa\src\NodeRSA.js:73:18)
    at Object.constructMessageSignature (C:\...\node_modules\samlify\build\src\libsaml.js:453:32)
    at buildRedirectURL (C:\...\node_modules\samlify\build\src\binding-redirect.js:82:80)     
    at Object.loginRequestRedirectURL (C:\...\node_modules\samlify\build\src\binding-redirect.js:121:22).

The issue stems from this call:
https://github.com/tngan/samlify/blob/b422c21a6162f3ad6d3ffa527a775d3f0edd4e3d/src/libsaml.ts#L547
```
const decryptedKey = new nrsa(
        utility.readPrivateKey(key, passphrase),
        'private',
        {
          signingScheme: getSigningScheme(signingAlgorithm),
        }
      );
```

In Node-RSA documentation, its stated it should be called like (note the array around key and format):
`const key = new NodeRSA([keyData, [format]], [options]);`
(https://github.com/rzcoder/node-rsa)

but as it is, it seems to be called:
`const key = new NodeRSA(keyData, [format], [options]);`

Not sure if this is a problem with the Node-RSA documentation not being correct, we tested this by changing the call as
```
var decryptedKey = new node_rsa_1.default([utility_1.default.readPrivateKey(key, passphrase), 'private'], {
                signingScheme: getSigningScheme(signingAlgorithm),
            });
```

The call seemed to work with this change, but I'm not sure about the repercussions (if its actually creating a private-format decrypted key or not (or if the problem is from somewhere else)
We use @authenio/samlify-xsd-schema-validator and Azure functions typescript implementation (typescript version 4.0.3)

Thank you very much for your time in advance

### PR DESCRIPTION
**Pull request by mastermatt**
Allow `node-rsa` to detect the format of the private key by not explicitly specifying an alias for the `pkcs1-private-pem` format. 
Reference [comment](https://github.com/tngan/samlify/issues/452#issuecomment-1359699318) for details.

Fixes #452

@tngan

### CODE REVIEW

**Comment by tngan** [comment]
@mastermatt thanks for the PR.

Is the new function `octetStringBuilder` only used in testing? 
The create request function should already return the octet string (which is the query).

**Comment by mastermatt** [comment]
@tngan `octetStringBuilder` is part of another change set Im working on, but it doesn't make sense to include it for this PR as, you are correct, it was only being used in the tests. I've I just pushed a commit that removes it and uses the `parseRedirectUrlContextCallBack` test helper instead.

File: test/index.ts [hunk 1]
```diff
@@ -334,13 +334,17 @@ test('getAssertionConsumerService with two bindings', t => {
...
     ],
     encryptCert: [
       readFileSync('./test/key/idp/encryptionCert.cer'),
       readFileSync('./test/key/idp/encryptionCert.cer').toString(),
-    ]
+    ],
+    singleSignOnService: [{
+      Binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
+      Location: 'idp.example.com/sso',
+    }]
```
Comment (mastermatt) [inline test/index.ts:347]: The fixes to this test are unrelated to the linked ticket. They are just typos from the last PR I contributed https://github.com/tngan/samlify/pull/499.

Comment (tngan) [reply test/index.ts:347]: okay

**Comment by tngan** [comment]
@mastermatt The change is valid, but I will make a remark in release where samlify only supports the key in PEM format.

> Notice: For import, if keyData is PEM string or buffer containing string, you can do not specify format, but if you provide keyData as DER you must specify it in format string.

PEM is the most common format now where DER is just a binary version, we can bring the support easily later on. 
Thanks for your nice work again.

**Comment by mastermatt** [comment]
@tngan could you publish a patch version to npm with this change please?

**Comment by tngan** [comment]
Sure, please check v2.8.9
